name: Build and Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prepare Release Archive
        run: |
          mkdir dist
          xcopy bin dist\bin /S /I
          xcopy lib dist\lib /S /I
          copy package.json dist\
          copy README.md dist\
          copy adb.exe dist\
          copy AdbWinApi.dll dist\
          copy AdbWinUsbApi.dll dist\
          Compress-Archive -Path dist\* -DestinationPath ADB-App-Remover-Node.zip

      - name: Generate Dynamic Tag
        id: generate_tag
        run: echo "TAG_NAME=v1.0.${{ github.run_number }}" >> $env:GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: ADB-App-Remover-Node.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
